//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using Ajuna.ServiceLayer.Attributes;
using Microsoft.AspNetCore.Mvc;
using MoneyPot_RestService.Generated.Storage;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace MoneyPot_RestService.Generated.Controller
{
    
    
    /// <summary>
    /// MoneyPotController controller to access storages.
    /// </summary>
    [ApiController()]
    [Route("[controller]")]
    public sealed class MoneyPotController : ControllerBase
    {
        
        private IMoneyPotStorage _moneyPotStorage;
        
        /// <summary>
        /// MoneyPotController constructor.
        /// </summary>
        public MoneyPotController(IMoneyPotStorage moneyPotStorage)
        {
            _moneyPotStorage = moneyPotStorage;
        }
        
        /// <summary>
        /// >> MoneyPotsCount
        /// </summary>
        [HttpGet("MoneyPotsCount")]
        [ProducesResponseType(typeof(Ajuna.NetApi.Model.Types.Primitive.U32), 200)]
        [StorageKeyBuilder(typeof(MoneyPot_NetApiExt.Generated.Storage.MoneyPotStorage), "MoneyPotsCountParams")]
        public IActionResult GetMoneyPotsCount()
        {
            return this.Ok(_moneyPotStorage.GetMoneyPotsCount());
        }
        
        /// <summary>
        /// >> MoneyPotsHash
        /// </summary>
        [HttpGet("MoneyPotsHash")]
        [ProducesResponseType(typeof(MoneyPot_NetApiExt.Generated.Model.primitive_types.H256), 200)]
        [StorageKeyBuilder(typeof(MoneyPot_NetApiExt.Generated.Storage.MoneyPotStorage), "MoneyPotsHashParams", typeof(Ajuna.NetApi.Model.Types.Primitive.U32))]
        public IActionResult GetMoneyPotsHash(string key)
        {
            return this.Ok(_moneyPotStorage.GetMoneyPotsHash(key));
        }
        
        /// <summary>
        /// >> MoneyPots
        /// </summary>
        [HttpGet("MoneyPots")]
        [ProducesResponseType(typeof(MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet.MoneyPot), 200)]
        [StorageKeyBuilder(typeof(MoneyPot_NetApiExt.Generated.Storage.MoneyPotStorage), "MoneyPotsParams", typeof(MoneyPot_NetApiExt.Generated.Model.primitive_types.H256))]
        public IActionResult GetMoneyPots(string key)
        {
            return this.Ok(_moneyPotStorage.GetMoneyPots(key));
        }
        
        /// <summary>
        /// >> MoneyPotOwned
        /// </summary>
        [HttpGet("MoneyPotOwned")]
        [ProducesResponseType(typeof(MoneyPot_NetApiExt.Generated.Model.sp_runtime.bounded.bounded_vec.BoundedVecT4), 200)]
        [StorageKeyBuilder(typeof(MoneyPot_NetApiExt.Generated.Storage.MoneyPotStorage), "MoneyPotOwnedParams", typeof(MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32))]
        public IActionResult GetMoneyPotOwned(string key)
        {
            return this.Ok(_moneyPotStorage.GetMoneyPotOwned(key));
        }
        
        /// <summary>
        /// >> MoneyPotContribution
        /// </summary>
        [HttpGet("MoneyPotContribution")]
        [ProducesResponseType(typeof(MoneyPot_NetApiExt.Generated.Model.sp_runtime.bounded.bounded_vec.BoundedVecT5), 200)]
        [StorageKeyBuilder(typeof(MoneyPot_NetApiExt.Generated.Storage.MoneyPotStorage), "MoneyPotContributionParams", typeof(MoneyPot_NetApiExt.Generated.Model.primitive_types.H256))]
        public IActionResult GetMoneyPotContribution(string key)
        {
            return this.Ok(_moneyPotStorage.GetMoneyPotContribution(key));
        }
    }
}
