//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.frame_support.weights
{
    
    
    /// <summary>
    /// >> 19 - Composite[frame_support.weights.DispatchInfo]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class DispatchInfo : BaseType
    {
        
        /// <summary>
        /// >> weight
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U64 _weight;
        
        /// <summary>
        /// >> class
        /// </summary>
        private MoneyPot_NetApiExt.Generated.Model.frame_support.weights.EnumDispatchClass _class;
        
        /// <summary>
        /// >> pays_fee
        /// </summary>
        private MoneyPot_NetApiExt.Generated.Model.frame_support.weights.EnumPays _paysFee;
        
        public Substrate.NetApi.Model.Types.Primitive.U64 Weight
        {
            get
            {
                return this._weight;
            }
            set
            {
                this._weight = value;
            }
        }
        
        public MoneyPot_NetApiExt.Generated.Model.frame_support.weights.EnumDispatchClass Class
        {
            get
            {
                return this._class;
            }
            set
            {
                this._class = value;
            }
        }
        
        public MoneyPot_NetApiExt.Generated.Model.frame_support.weights.EnumPays PaysFee
        {
            get
            {
                return this._paysFee;
            }
            set
            {
                this._paysFee = value;
            }
        }
        
        public override string TypeName()
        {
            return "DispatchInfo";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Weight.Encode());
            result.AddRange(Class.Encode());
            result.AddRange(PaysFee.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Weight = new Substrate.NetApi.Model.Types.Primitive.U64();
            Weight.Decode(byteArray, ref p);
            Class = new MoneyPot_NetApiExt.Generated.Model.frame_support.weights.EnumDispatchClass();
            Class.Decode(byteArray, ref p);
            PaysFee = new MoneyPot_NetApiExt.Generated.Model.frame_support.weights.EnumPays();
            PaysFee.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
