//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.frame_support.weights
{
    
    
    public enum Pays
    {
        
        Yes = 0,
        
        No = 1,
    }
    
    /// <summary>
    /// >> 21 - Variant[frame_support.weights.Pays]
    /// </summary>
    public sealed class EnumPays : BaseEnum<Pays>
    {
    }
}
