//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.frame_system.limits
{
    
    
    /// <summary>
    /// >> 56 - Composite[frame_system.limits.BlockWeights]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class BlockWeights : BaseType
    {
        
        /// <summary>
        /// >> base_block
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U64 _baseBlock;
        
        /// <summary>
        /// >> max_block
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U64 _maxBlock;
        
        /// <summary>
        /// >> per_class
        /// </summary>
        private MoneyPot_NetApiExt.Generated.Model.frame_support.weights.PerDispatchClassT2 _perClass;
        
        public Substrate.NetApi.Model.Types.Primitive.U64 BaseBlock
        {
            get
            {
                return this._baseBlock;
            }
            set
            {
                this._baseBlock = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Primitive.U64 MaxBlock
        {
            get
            {
                return this._maxBlock;
            }
            set
            {
                this._maxBlock = value;
            }
        }
        
        public MoneyPot_NetApiExt.Generated.Model.frame_support.weights.PerDispatchClassT2 PerClass
        {
            get
            {
                return this._perClass;
            }
            set
            {
                this._perClass = value;
            }
        }
        
        public override string TypeName()
        {
            return "BlockWeights";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(BaseBlock.Encode());
            result.AddRange(MaxBlock.Encode());
            result.AddRange(PerClass.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            BaseBlock = new Substrate.NetApi.Model.Types.Primitive.U64();
            BaseBlock.Decode(byteArray, ref p);
            MaxBlock = new Substrate.NetApi.Model.Types.Primitive.U64();
            MaxBlock.Decode(byteArray, ref p);
            PerClass = new MoneyPot_NetApiExt.Generated.Model.frame_support.weights.PerDispatchClassT2();
            PerClass.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
