using MoneyPot_NetApiExt.Generated;
using Shared_MoneyPot;

namespace MoneyPot_BlazorFront.Service
{
    public interface ISubstrateService
    {
        /// <summary>
        /// Substrate client generated by the Ajuna SDK
        /// </summary>
        public SubstrateClientExt Client { get;  }

        /// <summary>
        /// Is connected to blockchain
        /// </summary>
        public bool IsConnected { get; }

        /// <summary>
        /// Check every 'millisecondCheck' if we are connected to blockchain and call the callback method with status
        /// If we are not connected, try to reconnect
        /// </summary>
        /// <param name="isConnectedCallback">Callback status method</param>
        /// <param name="cancellationToken">Allow to stop the check</param>
        /// <param name="millisecondCheck">Millisecond frequency to check if we are connected and try to reconnect</param>
        /// <returns></returns>
        Task CheckBlockchainStateAsync(Action<bool> isConnectedCallback, CancellationToken cancellationToken, int millisecondCheck = 500);
    }
}
