//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.pallet_sudo.pallet
{
    
    
    public enum Call
    {
        
        sudo = 0,
        
        sudo_unchecked_weight = 1,
        
        set_key = 2,
        
        sudo_as = 3,
    }
    
    /// <summary>
    /// >> 117 - Variant[pallet_sudo.pallet.Call]
    /// Contains one variant per dispatchable that can be called by an extrinsic.
    /// </summary>
    public sealed class EnumCall : BaseEnumExt<Call, MoneyPot_NetApiExt.Generated.Model.node_template_runtime.EnumCall, BaseTuple<MoneyPot_NetApiExt.Generated.Model.node_template_runtime.EnumCall, Ajuna.NetApi.Model.Types.Primitive.U64>, MoneyPot_NetApiExt.Generated.Model.sp_runtime.multiaddress.EnumMultiAddress, BaseTuple<MoneyPot_NetApiExt.Generated.Model.sp_runtime.multiaddress.EnumMultiAddress, MoneyPot_NetApiExt.Generated.Model.node_template_runtime.EnumCall>>
    {
    }
}
