//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.pallet_sudo.pallet
{
    
    
    public enum Event
    {
        
        Sudid = 0,
        
        KeyChanged = 1,
        
        SudoAsDone = 2,
    }
    
    /// <summary>
    /// >> 41 - Variant[pallet_sudo.pallet.Event]
    /// 
    ///			The [event](https://docs.substrate.io/main-docs/build/events-errors/) emitted
    ///			by this pallet.
    ///			
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, MoneyPot_NetApiExt.Generated.Types.Base.EnumResult, Substrate.NetApi.Model.Types.Base.BaseOpt<MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32>, MoneyPot_NetApiExt.Generated.Types.Base.EnumResult>
    {
    }
}
