//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Types.Base
{
    
    
    public enum Result
    {
        
        Ok = 0,
        
        Err = 1,
    }
    
    /// <summary>
    /// >> 37 - Variant[Result]
    /// </summary>
    public sealed class EnumResult : BaseEnumExt<Result, Substrate.NetApi.Model.Types.Base.BaseTuple, MoneyPot_NetApiExt.Generated.Model.sp_runtime.EnumDispatchError>
    {
    }
}
