//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet
{
    
    
    public enum Event
    {
        
        Created = 0,
        
        Transfered = 1,
        
        MoneyAdded = 2,
        
        Closed = 3,
    }
    
    /// <summary>
    /// >> 43 - Variant[pallet_money_pot.pallet.Event]
    /// 
    ///			The [event](https://docs.substrate.io/main-docs/build/events-errors/) emitted
    ///			by this pallet.
    ///			
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, MoneyPot_NetApiExt.Generated.Model.primitive_types.H256, MoneyPot_NetApiExt.Generated.Model.primitive_types.H256, BaseTuple<MoneyPot_NetApiExt.Generated.Model.primitive_types.H256, MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>, MoneyPot_NetApiExt.Generated.Model.primitive_types.H256>
    {
    }
}
