//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet
{
    
    
    public enum AmountType
    {
        
        Native = 0,
        
        DOT = 1,
        
        USD = 2,
    }
    
    /// <summary>
    /// >> 128 - Variant[pallet_money_pot.pallet.AmountType]
    /// </summary>
    public sealed class EnumAmountType : BaseEnum<AmountType>
    {
    }
}
