//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet
{
    
    
    public enum Visibility
    {
        
        Everyone = 0,
        
        Restricted = 1,
    }
    
    /// <summary>
    /// >> 119 - Variant[pallet_money_pot.pallet.Visibility]
    /// </summary>
    public sealed class EnumVisibility : BaseEnum<Visibility>
    {
    }
}
