//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet
{
    
    
    public enum EndType
    {
        
        Time = 0,
        
        AmountReached = 1,
    }
    
    /// <summary>
    /// >> 127 - Variant[pallet_money_pot.pallet.EndType]
    /// </summary>
    public sealed class EnumEndType : BaseEnumExt<EndType, Substrate.NetApi.Model.Types.Primitive.U32, BaseTuple<MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet.EnumAmountType, Substrate.NetApi.Model.Types.Primitive.U128>>
    {
    }
}
