//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet
{
    
    
    /// <summary>
    /// >> 125 - Composite[pallet_money_pot.pallet.MoneyPot]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class MoneyPot : BaseType
    {
        
        /// <summary>
        /// >> owner
        /// </summary>
        private MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32 _owner;
        
        /// <summary>
        /// >> receiver
        /// </summary>
        private MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32 _receiver;
        
        /// <summary>
        /// >> start_time
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U32 _startTime;
        
        /// <summary>
        /// >> end_time
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseOpt<MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet.EnumEndType> _endTime;
        
        /// <summary>
        /// >> is_active
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.Bool _isActive;
        
        public MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32 Owner
        {
            get
            {
                return this._owner;
            }
            set
            {
                this._owner = value;
            }
        }
        
        public MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32 Receiver
        {
            get
            {
                return this._receiver;
            }
            set
            {
                this._receiver = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Primitive.U32 StartTime
        {
            get
            {
                return this._startTime;
            }
            set
            {
                this._startTime = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Base.BaseOpt<MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet.EnumEndType> EndTime
        {
            get
            {
                return this._endTime;
            }
            set
            {
                this._endTime = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Primitive.Bool IsActive
        {
            get
            {
                return this._isActive;
            }
            set
            {
                this._isActive = value;
            }
        }
        
        public override string TypeName()
        {
            return "MoneyPot";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Owner.Encode());
            result.AddRange(Receiver.Encode());
            result.AddRange(StartTime.Encode());
            result.AddRange(EndTime.Encode());
            result.AddRange(IsActive.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Owner = new MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32();
            Owner.Decode(byteArray, ref p);
            Receiver = new MoneyPot_NetApiExt.Generated.Model.sp_core.crypto.AccountId32();
            Receiver.Decode(byteArray, ref p);
            StartTime = new Substrate.NetApi.Model.Types.Primitive.U32();
            StartTime.Decode(byteArray, ref p);
            EndTime = new Substrate.NetApi.Model.Types.Base.BaseOpt<MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet.EnumEndType>();
            EndTime.Decode(byteArray, ref p);
            IsActive = new Substrate.NetApi.Model.Types.Primitive.Bool();
            IsActive.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
