//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.node_template_runtime
{
    
    
    public enum Call
    {
        
        System = 0,
        
        Timestamp = 2,
        
        Grandpa = 4,
        
        Balances = 5,
        
        Scheduler = 6,
        
        Sudo = 8,
        
        MoneyPot = 9,
    }
    
    /// <summary>
    /// >> 114 - Variant[node_template_runtime.Call]
    /// </summary>
    public sealed class EnumCall : BaseEnumExt<Call, MoneyPot_NetApiExt.Generated.Model.frame_system.pallet.EnumCall, BaseVoid, MoneyPot_NetApiExt.Generated.Model.pallet_timestamp.pallet.EnumCall, BaseVoid, MoneyPot_NetApiExt.Generated.Model.pallet_grandpa.pallet.EnumCall, MoneyPot_NetApiExt.Generated.Model.pallet_balances.pallet.EnumCall, MoneyPot_NetApiExt.Generated.Model.pallet_scheduler.pallet.EnumCall, BaseVoid, MoneyPot_NetApiExt.Generated.Model.pallet_sudo.pallet.EnumCall, MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet.EnumCall>
    {
    }
}
