//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.node_template_runtime
{
    
    
    public enum OriginCaller
    {
        
        system = 0,
        
        Void = 1,
    }
    
    /// <summary>
    /// >> 119 - Variant[node_template_runtime.OriginCaller]
    /// </summary>
    public sealed class EnumOriginCaller : BaseEnumExt<OriginCaller, MoneyPot_NetApiExt.Generated.Model.frame_support.dispatch.EnumRawOrigin, Ajuna.NetApi.Model.Types.Base.BaseVoid>
    {
    }
}
