//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.node_template_runtime
{
    
    
    public enum Event
    {
        
        System = 0,
        
        Grandpa = 4,
        
        Balances = 5,
        
        Scheduler = 6,
        
        TransactionPayment = 7,
        
        Sudo = 8,
        
        MoneyPot = 9,
    }
    
    /// <summary>
    /// >> 17 - Variant[node_template_runtime.Event]
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, MoneyPot_NetApiExt.Generated.Model.frame_system.pallet.EnumEvent, BaseVoid, BaseVoid, BaseVoid, MoneyPot_NetApiExt.Generated.Model.pallet_grandpa.pallet.EnumEvent, MoneyPot_NetApiExt.Generated.Model.pallet_balances.pallet.EnumEvent, MoneyPot_NetApiExt.Generated.Model.pallet_scheduler.pallet.EnumEvent, MoneyPot_NetApiExt.Generated.Model.pallet_transaction_payment.pallet.EnumEvent, MoneyPot_NetApiExt.Generated.Model.pallet_sudo.pallet.EnumEvent, MoneyPot_NetApiExt.Generated.Model.pallet_money_pot.pallet.EnumEvent>
    {
    }
}
