//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.frame_support.traits.schedule
{
    
    
    public enum MaybeHashed
    {
        
        Value = 0,
        
        Hash = 1,
    }
    
    /// <summary>
    /// >> 113 - Variant[frame_support.traits.schedule.MaybeHashed]
    /// </summary>
    public sealed class EnumMaybeHashed : BaseEnumExt<MaybeHashed, MoneyPot_NetApiExt.Generated.Model.node_template_runtime.EnumCall, MoneyPot_NetApiExt.Generated.Model.primitive_types.H256>
    {
    }
}
