//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace MoneyPot_NetApiExt.Generated.Model.frame_support.traits.schedule
{
    
    
    public enum LookupError
    {
        
        Unknown = 0,
        
        BadFormat = 1,
    }
    
    /// <summary>
    /// >> 39 - Variant[frame_support.traits.schedule.LookupError]
    /// </summary>
    public sealed class EnumLookupError : BaseEnum<LookupError>
    {
    }
}
